export const INCREAMENT_COUNTER = "INCREAMENT_COUNTER";
export const DECREAMENT_COUNTER = "DECREAMENT_COUNTER";
export const INCREAMENT_COUNTER_SOLVED = "INCREAMENT_COUNTER_SOLVED";
export const DECREAMENT_COUNTER_SOLVED = "DECREAMENT_COUNTER_SOLVED";
