export const INCREAMENT_COUNTER = "INCREAMENT_COUNTER";
export const DECREAMENT_COUNTER = "DECREAMENT_COUNTER";
export const INCREAMENT_COUNTER_SOLVED = "INCREAMENT_COUNTER_SOLVED";
export const DECREAMENT_COUNTER_SOLVED = "DECREAMENT_COUNTER_SOLVED";

export const GET_ALL_COUNTRY_IN_PROGRESS = "GET_ALL_COUNTRY_IN_PROGRESS";
export const GET_ALL_COUNTRY_SUCCESS = "GET_ALL_COUNTRY_SUCCESS";
export const GET_ALL_COUNTRY_FAILED = "GET_ALL_COUNTRY_FAILED";

export const GET_COUNTRY_REGIONS_IN_PROGRESS = "GET_COUNTRY_REGIONS_IN_PROGRESS";
export const GET_COUNTRY_REGIONS_SUCCESS = "GET_COUNTRY_REGIONS_SUCCESS";
export const GET_COUNTRY_REGIONS_FAILED = "GET_COUNTRY_REGIONS_FAILED";

export const GET_REGION_CITIES_IN_PROGRESS = "GET_REGION_CITIES_IN_PROGRESS";
export const GET_REGION_CITIES_SUCCESS = "GET_REGION_CITIES_SUCCESS";
export const GET_REGION_CITIES_FAILED = "GET_REGION_CITIES_FAILED";

export const GET_WEATHER_IN_PROGRESS = "GET_WEATHER_IN_PROGRESS";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAILED = "GET_WEATHER_FAILED";

export const SIGN_UP_IN_PROGRESS = "SIGN_UP_IN_PROGRESS";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const CHECK_AUTH_IN_PROGRESS = "CHECK_AUTH_IN_PROGRESS";
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAILED = "CHECK_AUTH_FAILED";

export const LOGOUT_IN_PROGRESS = "LOGOUT_IN_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const FACEBOOK_LOGIN_IN_PROGRESS = "FACEBOOK_LOGIN_IN_PROGRESS";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAILED = "FACEBOOK_LOGIN_FAILED";

export const GOOGLE_LOGIN_IN_PROGRESS = "GOOGLE_LOGIN_IN_PROGRESS";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILED = "GOOGLE_LOGIN_FAILED";

export const GITHUB_LOGIN_IN_PROGRESS = "GITHUB_LOGIN_IN_PROGRESS";
export const GITHUB_LOGIN_SUCCESS = "GITHUB_LOGIN_SUCCESS";
export const GITHUB_LOGIN_FAILED = "GITHUB_LOGIN_FAILED";

export const LISTENER_ALL_USERS_IN_PROGRESS = "LISTENER_ALL_USERS_IN_PROGRESS";
export const LISTENER_ALL_USERS_SUCCESS = "LISTENER_ALL_USERS_SUCCESS";
export const LISTENER_ALL_USERS_FAILED = "LISTENER_ALL_USERS_FAILED";
export const LISTENER_ALL_USERS_CANCEL = "LISTENER_ALL_USERS_CANCEL";

export const SUBSCRIPTION_IN_PROGRESS = "SUBSCRIPTION_IN_PROGRESS";
export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";
export const SUBSCRIPTION_FAILED = "SUBSCRIPTION_FAILED";

export const UNSUBSCRIBE_IN_PROGRESS = "UNSUBSCRIBE_IN_PROGRESS";
export const UNSUBSCRIBE_SUCCESS = "UNSUBSCRIBE_SUCCESS";
export const UNSUBSCRIBE_FAILED = "UNSUBSCRIBE_FAILED";
