export const INCREAMENT_COUNTER = "INCREAMENT_COUNTER";
export const DECREAMENT_COUNTER = "DECREAMENT_COUNTER";
export const INCREAMENT_COUNTER_SOLVED = "INCREAMENT_COUNTER_SOLVED";
export const DECREAMENT_COUNTER_SOLVED = "DECREAMENT_COUNTER_SOLVED";

export const GET_ALL_COUNTRY_IN_PROGRESS = "GET_ALL_COUNTRY_IN_PROGRESS";
export const GET_ALL_COUNTRY_SUCCESS = "GET_ALL_COUNTRY_SUCCESS";
export const GET_ALL_COUNTRY_FAILED = "GET_ALL_COUNTRY_FAILED";

export const GET_COUNTRY_REGIONS_IN_PROGRESS = "GET_COUNTRY_REGIONS_IN_PROGRESS";
export const GET_COUNTRY_REGIONS_SUCCESS = "GET_COUNTRY_REGIONS_SUCCESS";
export const GET_COUNTRY_REGIONS_FAILED = "GET_COUNTRY_REGIONS_FAILED";

export const GET_REGION_CITIES_IN_PROGRESS = "GET_REGION_CITIES_IN_PROGRESS";
export const GET_REGION_CITIES_SUCCESS = "GET_REGION_CITIES_SUCCESS";
export const GET_REGION_CITIES_FAILED = "GET_REGION_CITIES_FAILED";

export const GET_WEATHER_IN_PROGRESS = "GET_WEATHER_IN_PROGRESS";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAILED = "GET_WEATHER_FAILED";

export const SIGN_UP_IN_PROGRESS = "SIGN_UP_IN_PROGRESS";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const CHECK_AUTH_IN_PROGRESS = "CHECK_AUTH_IN_PROGRESS";
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAILED = "CHECK_AUTH_FAILED";

export const LOGOUT_IN_PROGRESS = "LOGOUT_IN_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
